### PR TITLE
Adds Documentation Checklist

### PR DESCRIPTION
**Pull request by SimaoBolota-MetaCell**
The intent of this utility is to check your plugin for specific metadata in the Napari recommended file location. 
With this, it creates a **Documentation Checklist** identifying the following metadata:

- Display Name
- Summary Sentence
- Intro Paragraph
- Intro Video
- Intro Scrennshot
- Usage Section
- Source Code Link
- User Support Link
- Bug Tracker Link
- Author
- Citation

Additionally, the recommended file locations are suggested in two different cases:

- when no metadata is found in either the primary file location or the fallback file location
- when no metadata is found at the primary file location

Below you can find a table with the metadata and its associated primary recommended files and fallback files:

Metadata / Files | Primary File | Fallback File(s) 
--- | --- | --- | 
Display Name | ```npe2``` | ```setup.cfg```  or ```setup.py```
Summary Sentence | ```napari-hub/config.yml``` | ```setup.cfg```  or ```setup.py``` 
Intro Paragraph | ```napari-hub/description.md``` | ```setup.cfg```  or ```setup.py``` 
Intro Video | ```napari-hub/description.md``` | ```setup.cfg```  or ```setup.py``` 
Intro Screenshot | ```napari-hub/description.md``` | ```setup.cfg```  or ```setup.py``` 
Usage Section | ```napari-hub/description.md``` | ```setup.cfg```  or ```setup.py``` 
Source Code Link | ```napari-hub/config.yml``` | ```setup.cfg```  or ```setup.py``` 
User Support Link | ```napari-hub/config.yml``` | ```setup.cfg```  or ```setup.py``` 
Bug Tracker Link | ```napari-hub/config.yml``` | ```setup.cfg```  or ```setup.py``` 
Author | ```napari-hub/config.yml``` | ```setup.cfg```  or ```setup.py``` 
Citation | ```.cff``` | ```-``` 

# Usage

To create the Napari Documentation Checklist for your plugin run

```
 $ napari-hub-cli create-doc-checklist /tmp/example-plugin 
```
having first installed all the requirements for ```napari-hub-cli```.

### CODE REVIEW

**Comment by neuromusic** [comment]
Thanks @SimaoBolota-MetaCell !! One concern is that the wiki is out of date re: preferred sources. I will get this updated then review this PR in more depth.

**Comment by neuromusic** [comment]
updated reference: https://github.com/chanzuckerberg/napari-hub/wiki/Customizing-your-plugin's-listing

**Comment by SimaoBolota-MetaCell** [comment]
Thank you @neuromusic . Will update the code in this PR considering the new preferred sources and when finished I'll let you know.

**Comment by aranega** [comment]
The PR now fixes #29 and also provides:

* an analysis of remote repository with the `check-plugin` command,
* an analysis of all repositories with the output in a CSV format with the `all-plugins-report` command.

All elements of the check-list are tested/checked against the updated "prefered sources". 

The PR also include a refactoring of the abstraction used to deal with configuration files and to detect some patterns in files.

The PR still misses more tests and to check that function/method documentation is in-sync with last modifications.

**Pull request merged**
